#!/usr/bin/env python3

from os import listdir, path
from os.path import isfile

open('index.html','w').write("""\
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="content-type">
	<title>Lessons</title>
</head>

<body>
{}
</body>

""".format('\n'.join(["<a href='{0}'>{0}</a><br>".format(f) for f in listdir('.') if isfile(f) and f.endswith('.xml')])))
